services:
  spatialfin-companion:
    build: .
    container_name: spatialfin-companion
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./data:/app/data
    restart: unless-stopped
